[package]
name = "day01"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
clio = { workspace = true }

[[bin]]
name = "day01-part1"

[[bin]]
name = "day01-part2"
