[package]
name = "day04"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
clio = { workspace = true }
rayon = { workspace = true }
num_cpus = { workspace = true }

[[bin]]
name = "day04-part1"

[[bin]]
name = "day04-part2"
